### ISSUE TITLE
How can I expose a Marathon endpoint for my Marathon cluster

### ISSUE THREAD

**Issue by doctapp** [mesosphere/mesos-dns#114]
Would be really useful to know how to have a known Marathon endpoint for a set of Marathon masters. This way, I could have a single highly-available endpoint for launching Marathon apps.
Thanks

**Comment by kozyraki** [comment]
@doctapp let me investigate this a little and get back to you. 
There are a number of issues here:
- how was Marathon launched. If it was launched through Mesos (runs on slaves etc) then Mesos-DNS knows about it. Otherwise, Mesos-DNS is clueless. 
- what is the endpoint you care about and how do you want it advertised. We can stick anything in a TXT record and we are also adding an http interface. But if you want a redirection, it has implications. 
Share your thoughts on these issues.

**Comment by doctapp** [comment]
Thanks for the info. Marathon is started as a local service on the mesos masters. Since it's a framework, I don't understand how mesos it can be launched otherwise. Does moving this process to slaves the recommended way?

The endpoint I care about is marathon's REST API since I want to have a highly available way of starting and stopping apps. I would like this advertised as a single endpoint backed by multiple marathon masters and I don't want my apps to know about all marathon masters for this purpose.

Does this info help you understand my need better?

**Comment by kensipe** [comment]
@doctapp to clarify... marathon running on the slaves isn't sufficient for it to register with mesos-dns.   What was meant, is that marathon is launched as a task by mesos on a slave.   Although it may seem odd... it would be possible for instance to launch marathon (m2) with a "master" marathon (m1).     The m2 marathon would be registered in mesos-dns because it is launched by mesos onto a slave.   

@kozyraki it would be nice to have frameworks A records regardless...   This is a good example.   It would be great if `marathon.mesos.` returned the IPs of marathons regardless of how they were run...

**Comment by doctapp** [comment]
@kensipe thanks for the clarification, that's a good hack. Would definitely be great if there was a reliable way of getting the marathon endpoints.

**Comment by tsenart** [comment]
Fixed by https://github.com/mesosphere/mesos-dns/pull/209
