### ISSUE TITLE
Load balancing with Mesos-dns

### ISSUE THREAD

**Issue by wiselyman** [mesosphere/mesos-dns#130]
I deploy mesos-dns through marathon ui on one slave machine(192.168.1.1.113)
- command: `/usr/local/mesos-dns/mesos-dns --v=0 -config=/usr/local/mesos-dns/config.json`
- constraints:`hostname:CLUSTER:192.168.1.113`
- config.json:
```
{
  "zk": "zk://192.168.1.110:2181,192.168.1.111:2181,192.168.1.112:2181/mesos",
  "masters": ["192.168.1.110:5050","192.168.1.111:5050","192.168.1.112:5050"],
  "refreshSeconds": 60,
  "ttl": 60,
  "domain": "mesos",
  "port": 53,
  "resolvers": ["169.254.169.254"],
  "timeout": 5,
  "listener": "192.168.1.113",
  "email": "root.mesos-dns.mesos"
}
```

I have a "test" app with command of  `python -m SimpleHTTPServer $PORT` and scale of 4.

When i input `dig test.marathon.mesos` shows:
```
; <<>> DiG 9.9.6-P1-RedHat-9.9.6-8.P1.fc21 <<>> test.marathon.mesos
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39311
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;test.marathon.mesos.           IN      A

;; ANSWER SECTION:
test.marathon.mesos.    60      IN      A       192.168.1.115
test.marathon.mesos.    60      IN      A       192.168.1.113
test.marathon.mesos.    60      IN      A       192.168.1.114

;; Query time: 1 msec
;; SERVER: 192.168.1.113#53(192.168.1.113)
;; WHEN: Fri Apr 17 10:57:24 CST 2015
;; MSG SIZE  rcvd: 142
```

when I accessed:"http://test.marathon.mesos" nothing showed
when I accessed with an port,page showed.
how can i fullfill load-balancing using mesos-dns

**Comment by kozyraki** [comment]
@wiselyman Thanks for using mesos-dns. 

A few tips:
1) you said that you have scaled the app x4, but mesos DNS seems to have only 3 addresses. This may be because you have all 4 tasks issued on 3 nodes. Do double-check and let me know what is the case. 

2) While A records get you and IP address, the do not get you a port. Here is what I suggest. First use "dig SRV _test._tcp.marathon.mesos" to get a number of entries that tell you an address AND an port you can you. You will see 4 entries hopefully. Let say that one of the address is x:y where x is a hostname/IP port and y is a port. Then, use "curl http://x:y", that will hopefully give you an output. 

3) I strongly suggest you start using the http branch of Mesos-DNS. It has a number of features you will like (e.g. http access to A and SRV records) and a number of bug fixes. 

Hope this helps.

**Comment by wiselyman** [comment]
@kozyraki 

Thanks for your reply.
I just want an load-balancer,can only using mesos-dns complete this mission?
can http branch of mesos-dns do this ?

**Comment by kozyraki** [comment]
Mesos-dns will give you VERY BASIC load balancing.
Every time you access DNS, it will randomly shuffle the entries that much
to that name. So, if you always use the first IP address, you will see a
random shuffle every time. That's all.
