### ISSUE TITLE
generator.go:74: no master

### ISSUE THREAD

**Issue by mconigliaro** [mesosphere/mesos-dns#186]
The documentation says "It is sufficient to specify just one of the zk or masters field," and "We recommend you use the zk field since this allows the dynamic addition to Mesos masters."

I'm not sure if this indicates a problem, but not setting the masters field results in a `generator.go:74: no master` error.

**Comment by sargun** [comment]
Is this still the case? I think d35dd1f4 should have fixed this, since it adds a master: "" to the list - although you can still get a refresh cycle with no masters, it'll eventually converge once it gets the list from Zookeeper.

**Comment by sargun** [comment]
@s-urbaniak Might you be able to comment on this?

**Comment by s-urbaniak** [comment]
@mconigliaro sorry about the very late reply, but indeed the mesos-dns codebase changed quite a bit since your question.

The current version of mesos-dns (v0.4.0 and up) indeed does not print this message any more (as it was misleading) and as @sargun already correctly explains the initial master is the empty string `""` eventually converging once zookeper gives us the necessary information.

The `ERROR: ... no master` message should now only appear in a real erroneous case only, i.e when timeouts or connection issues to ZooKeeper and/or Mesos occur.
