### ISSUE TITLE
Proposal: Container image

### ISSUE THREAD

**Issue by ahmetalpbalkan** [mesosphere/mesos-dns#265]
Is there a reason why this is not containerized? Looks like everybody is compiling this and running it on marathon. Instead it could've been `docker run -d -p 53:53 mesos-dns` ?

**Comment by karlkfi** [comment]
There's a containerizer here: https://github.com/mesosphere/mesos-dns-pkg Tho it's not well used and has a few issues. 

I'm not sure what happened to the original author...

**Comment by cmaloney** [comment]
Author has been out sick for a while

**Comment by ahmetalpbalkan** [comment]
That looks quite a lot complicated. I think this repo just needs a Dockerfile that uses golang base image and builds the mesos-dns and sets the entrypoint. I fail to see point of a minimalist image. Also it'll be hard to get that image rebuilt automatically on Docker Hub when this repo has new commits. 

I think it should be a single Dockerfile this repo.

**Comment by karlkfi** [comment]
I don't necessarily disagree. Was just pointing you at what we have.

The primary motivation around a minimalist image is to reduce size of the image to speed up shipping it over the wire. But there's a cost to be paid in increasing the difficulty of debugging too.

I personally would recommend Alpine as a base-image, because it's the smallest thing with a package manager, which means you can install more tools at runtime if you need.

That said, I know that DNS resolution is handled differently on different OSes. So the OS we statically compile against might matter. Tho I also know DNS/hostname resolution changed in Go 1.5. So maybe it's not an issue anymore... not sure.

Anyway, I suspect we at least need two dockerfiles. One that builds (and can cross-compile to produce release binaries), and one that just adds the binary to a small base image.

I suspect we'd consider a PR, if you're interested, but I can't speak for @lloesche or @tsenart. They might have other plans.

**Comment by tsenart** [comment]
It's trivial to download and run the pre-compiled Mesos-DNS executables found in https://github.com/mesosphere/mesos-dns/releases.

For possible future integration testing, with the necessity to orchestrate multiple pieces of infrastructure, using something like Docker compose would help us out, specially with the expertise that @karlkfi and @sttts already have with it, but for now, I don't see the necessity to containerise Mesos-DNS with Docker.

**Comment by ahmetalpbalkan** [comment]
I see. I suggest documenting the fact that downloadable executables exist at /releases in the docs: https://mesosphere.github.io/mesos-dns/docs/ I wasn't aware.

**Comment by tsenart** [comment]
@ahmetalpbalkan: You're absolutely right. I have to address this soon: https://github.com/mesosphere/mesos-dns/issues/264

**Comment by tsenart** [comment]
Ref: https://github.com/mesosphere/mesos-dns/issues/331
