### ISSUE TITLE
Crashing when goroutine count is very high

### ISSUE THREAD

**Issue by eyberg** [mesosphere/mesos-dns#54]
```
goroutine 102572 [runnable]:
github.com/miekg/dns.(*Server).serve(0xc20801ed00, 0x63b610, 0xc214e33f20, 0x63b5c0, 0xc20802a610, 0xc20ccb1a00, 0x23, 0x200, 0xc2080440a8, 0xc20cd9d6e0, ...)
        /Users/ianeyberg/go/src/github.com/miekg/dns/server.go:427
created by github.com/miekg/dns.(*Server).serveUDP
        /Users/ianeyberg/go/src/github.com/miekg/dns/server.go:421 +0x285

rax     0x0
rbx     0x6
rcx     0xb0080bd8
rdx     0x0
rdi     0xa03
rsi     0x6
rbp     0xb0080c00
rsp     0xb0080bd8
r8      0xb0080ae0
r9      0xb0081000
r10     0x8000000
r11     0x206
r12     0x7fff7cfe5070
r13     0xd3220461630
r14     0xb0081000
r15     0xb0080c58
rip     0x7fff8f80a282
rflags  0x206
cs      0x7
fs      0x0
gs      0x0
```

```
#!/bin/bash
for i in `seq 1 10`;
do
  ./resperf -s127.0.0.1 -p8053 -d queryfile-example-current -m 10000 -r 100
done
```

**Comment by tsenart** [comment]
Is this still relevant?

**Comment by jdef** [comment]
I believe that it is, at least architecturally. The underlying miekg/dns server library spawns go-routines for:
- each new tcp connection
- each new udp request

**Comment by tsenart** [comment]
@jdef: That shouldn't really be a problem. I believe the native `net/http` package does the same. I'm more interested in reliably replicating this condition. If it can't be replicated, then this issue should be closed.

**Comment by tsenart** [comment]
This thread gave me some insight into this issue. https://groups.google.com/d/msg/golang-nuts/_zK0_8mt2qQ/1HsjAHnSQFQJ

> You're running out of threads. 
Which means either: 
* The allowable threads per process on your machine in really low 
* You set GOMAXPROCS really high 
or more likely you've got a lot of threads blocking on syscalls or CGO calls. 

> I can't tell from your stacktrace, but I'm going to guess this is DNS 
lookup related. 
Most system DNS resolvers are blocking CGO calls that will tie up a 
thread for the 
time required to perform the DNS loop. 

> If you need to use the system DNS resolver(because you need access to 
it's config, dhcp provided nameservers etc.) then your best option is 
to 
ratelimit the number of connections your proxy will accept to a number 
within your thread limit. 

> Otherwise you can build the net pkg without CGO support and it will 
fall back to using the pure 
Go DNS resolver which should perform better. 

We were likely running out of threads during this load test. Setting the appropriate `ulimits` would alleviate the problem but what we should really do is to statically compile `mesos-dns` so that we don't use the CGO based DNS resolvers. This has always been possible but in Go 1.5 is the default: http://tip.golang.org/doc/go1.5#net

This should also be a good opportunity to review the DNS queries we're doing. In the current master, we only do DNS queries during state reloads to lookup [framework](https://github.com/mesosphere/mesos-dns/blob/master/records/generator.go#L208) and [slave](https://github.com/mesosphere/mesos-dns/blob/master/records/generator.go#L224) hostnames.

**Comment by kozyraki** [comment]
No clear if this is still relevant.
Ian had observed this in some experiments, but I had a hard time reproducing it. I left it there in case it shows up again.

**Comment by tsenart** [comment]
@kozyraki: As commented, I'm pretty sure this will go away under the described conditions.

**Comment by tsenart** [comment]
Verified that it's not happening anymore with Go 1.5 DNS resolution.
