### ISSUE TITLE
Default port?

### ISSUE THREAD

**Issue by pcj** [mesosphere/mesos-dns#63]
## Question

The docs suggest using port `53`, but the `config.json.sample` file defaults to `8053`.  Any reason for this confusion?

## Log
1. Spun up a development 1 master 3 slave DO cluster using mesophere interface.  OK.  Debian GNU/Linux 7 (wheezy).

1. `go get github.com/miekg/dns` failed with syntax error.  Annoyingly, `go version` is `1.0.3` and `apt-get golang` no better, so had to build go from source.   Successfully built go `1.4.1` from instructions at https://golang.org/doc/install/source.  `export GOROOT=/root/github.com/go` in my case.

1.  Followed these instructions to build mesos-dns. http://mesosphere.github.io/mesos-dns/docs/  http://mesosphere.github.io/mesos-dns/docs/configuration-parameters.html.  

```
$ go get github.com/mesosphere/mesos-dns
$ go get github.com/miekg/dns
$ go build -o mesos-dns main.go
$ cp mesos-dns /usr/local/bin # with other mesos tools
$ cp config.json.sample /etc/mesos/mesos-dns.json # seems reasonable
$ vi /etc/mesos-dns.json
```

**Comment by kozyraki** [comment]
I changed the default although you should be VERY careful with the values in this file. The examples may be quite bad for you. For instances, in some tests we've seen clusters that misbehave when using the Google public DNS [8.8.8.8] instead of whatever used to be the nameserver in /etc/resolv.conf.
