### ISSUE TITLE
Create example 'hello world' application that uses mesos-dns for service discovery.

### ISSUE THREAD

**Issue by pcj** [mesosphere/mesos-dns#68]
It would be very useful to have an example application (perhaps a docker container) that demonstrates how service discovery is performed using mesos-dns A and SRV records.

This would also help users confirm they have a successful install & config.

**Comment by kozyraki** [comment]
Take a look at http://mesosphere.github.io/mesos-dns/docs/tutorial-gce.html
Let me know if there are any issues with these instructions.

**Comment by pcj** [comment]
@kozyraki Looks great!  In step 3 addendum (or somewhere), I recommend mentioning that running mesos-dns with the `-v=true` option will dump out the existing _expected name_ `nginx.marathon-0.7.6.mesos` (or whatever this triplet identifier is called).

As a new user, I got it up and running fairly easily, but it was unclear what those expected names actually are, and if there is any character substitution to be anticipated.  In fact, the character space for framework names is a superset of the allowed characters in a domain name, so I expect you may want to offer some normalization scheme for disallowed characters (like space).

For example, this is one of my task identifiers as calculated by mesos-dns:

```
task1421952328345.Cassandra development cassandra cluster.mesos
```

But that's not valid domain name, and thus cannot be discovered as is (I think that's true, could be wrong).  Using the ``--framework-name` option is a workaround (as you mentioned in the tutorial), but it may be valuable to translate this to `task1421952328345.Cassandra_development_cassandra_cluster.mesos`.  Perhaps there is a go lib function that does this already.

**Comment by kozyraki** [comment]
@pcj Good point about -v. I have updated the documents. 

About the task/framework names now. Mesos-DNS has no control over the type and complexity of names used for registered frameworks and launched tasks. All we can do is recommend the use of reasonable names so that the A and SRV records are reasonable. Over the time, especially when the Mesos protobufs update for service discovery make it to a release, this will improve. Check the other issue where we ask for community feedback on naming scheme. 

About the space in the framework name: we should be removing space and other illegal characters for hostnames. This seems like a bug. Please file an separate issue.

**Comment by alexraju** [comment]
https://github.com/kozyraki
http://mesosphere.github.io/mesos-dns/docs/tutorial-gce.html link is not working anymore.
