### ISSUE TITLE
bootstrap slave vs. auto-configure.

### ISSUE THREAD

**Issue by timothysc** [mesosphere/mesos-dns#74]
Couldn't the slave mount /etc/resolv.conf instead of requiring a change on the slave host?

**Comment by tsenart** [comment]
What is this issue about? I can't understand from the given context.

**Comment by jdef** [comment]
I'm guessing this is talking about mounting a custom resolv.conf inside a tasks container (mount namespace) so that DNS clients operating within the task container use a customized resolv.conf that points to mesos-dns, and then the slave host's resolv.conf remains unchanged.

kubernetes supports this via a flag in the pod descriptor.

**Comment by sttts** [comment]
No need to mount anything. docker-run supports that.

**Comment by tsenart** [comment]
How is this related to mesos-dns?

**Comment by tsenart** [comment]
AFAICT this has nothing to do with `mesos-dns` itself and everything to do with how Mesos nodes have their `/etc/resolv.conf` configured.

**Comment by timothysc** [comment]
@jdef is spot on.. That enables a single host to potentially resolve across different networks.

**Comment by jdef** [comment]
this functionality sounds like a candidate for a mesos module, if not to be included in the mesos native containerizer itself (and possibly the docker containerizer as well).

@sttts yes, docker supports doing these things but the docker containerizer in mesos doesn't take any steps to make this happen - the user is required to do this manually for every container that they launch. kubernetes makes things like this much more streamlined for users.
